name: Downstream Trigger

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr-source:
    name: Check PR Source Branch
    runs-on: self-hosted
    outputs:
      is_from_dev: ${{ steps.check_branch.outputs.is_from_dev }}
    steps:
      - name: Check if workflow is operating from dev branch
        id: check_branch
        run: |
          IS_FROM_DEV="false"
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.head_ref }}" == "dev" ]]; then
            IS_FROM_DEV="true"
            echo "This is a pull request coming from the dev branch into main."
          else
            echo "This PR is not from dev to main (PR head: ${{ github.head_ref }}, PR base: ${{ github.base_ref }}). Downstream staging will be skipped."
          fi
          echo "is_from_dev=$IS_FROM_DEV" >> $GITHUB_OUTPUT
          echo "Branch check result: is_from_dev = $IS_FROM_DEV"

  run-tests:
    name: Run Pytest Comparison
    uses: JamesonRGrieve/Workflows/.github/workflows/test-pytest.yml@main
    with:
      target_branch_to_compare: ${{ github.base_ref }}
    permissions:
      contents: write

  run-bandit-check:
    name: Run Bandit Regression Workflow
    uses: JamesonRGrieve/Workflows/.github/workflows/test-bandit.yml@main
    with:
      target_branch_to_compare: ${{ github.base_ref }} # Usually 'main' in PRs to main
    permissions:
      contents: read

  call-reusable-stage-downstream:
    name: Call Reusable Stage Downstream Workflow
    needs: [check-pr-source, run-tests, run-bandit-check]
    if: needs.check-pr-source.outputs.is_from_dev == 'true'
    uses: JamesonRGrieve/Workflows/.github/workflows/test-downstream.yml@main
    with:
      source_repo_ref: "dev"
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      DOWNSTREAM_REPOSITORIES: ${{ secrets.DOWNSTREAM_REPOSITORIES }}
    permissions:
      contents: write
      pull-requests: write
