name: Lint Trigger

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  call-reusable-lint:
    name: Call Reusable Lint Workflow
    uses: JamesonRGrieve/Workflows/.github/workflows/test-lint-ts.yml@main
    # No specific inputs needed for the reusable lint workflow
    # Permissions are handled by the reusable workflow itself or should be inherited.
    # If secrets were needed, they would be passed here like:
    # secrets: inherit
