name: Trigger Submodule Management

on:
  push:
    branches:
      - main
      - dev

jobs:
  call-manage-submodules:
    name: Call Reusable Submodule Management
    # Make sure the reusable workflow is in the same repository at this path
    # or use <owner>/<repo>/.github/workflows/manage-submodules.yml@<ref> if it's in a central repo.
    uses: JamesonRGrieve/Workflows/.github/workflows/manage-submodules.yml@main
    with:
      # REQUIRED: Customize this list of comma-separated file paths
      # These are the files that will be synced from the main repository to the submodules
      # (when on a non-main branch, e.g., 'dev').
      file_paths: 'README.md,src/shared-config.json,docs/API.md'

      # OPTIONAL: Comma-separated list of submodule names/paths to ignore
      # ignore_submodules: "submodule1,path/to/submodule2"

      # OPTIONAL: Custom commit message for changes pushed to submodules (on non-main branches)
      # commit_message: "chore: sync shared files from parent repository"
    secrets: inherit # Ensures GITHUB_TOKEN and any other necessary secrets are passed
    # The reusable workflow `manage-submodules.yml` already defines its own permissions (contents: write).
    # If it didn't, you might need to specify them here.
