name: Reusable Build and Test Next.js

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use for build and test"
        required: false
        type: string
        default: "20"
      runs_on:
        required: false
        type: string
        default: "self-hosted"
jobs:
  lint:
    uses: ./.github/workflows/test-ts-lint.yml
    permissions:
      contents: write
    with:
      lint_command: "npm run lint"
      fix_command: "npm run lint-fix"
  build-baremetal:
    runs-on: ${{ inputs.runs_on }}
    name: Build / Baremetal
    needs: lint
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: "recursive"
          fetch-depth: 1
      - name: Check Submodules
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing current directory contents:"
          ls -a
          echo "\nChecking status of all submodules:"
          git submodule foreach --quiet ' \
            echo "\n--- Submodule: $name ---"; \
            echo "Path: $path"; \
            echo "Current directory: $(pwd)"; \
            echo "Listing contents:"; \
            ls -a; \
            echo "Remote URLs:"; \
            git remote -v; \
            echo "Status:"; \
            git status; \
            echo "---------------------------" \
          '
      - name: Install Packages and Build
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ inputs.node-version }}

      - run: |
          npm i lightningcss-linux-x64-gnu @tailwindcss/oxide-linux-x64-gnu sass-embedded-linux-x64
          npm i
          npm list zod --depth=0
          npm run build

      - name: Run Pytest
        id: pytest
        run: |
          pytest || echo "Tests failed"
        continue-on-error: true  

      - name: Label PR - Passed
        if: ${{ success() && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: unit-test-passed

      - name: Remove Failed Label if Present
        if: ${{ success() && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: unit-test-failed

      - name: Label PR - Failed
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: unit-test-failed

      - name: Remove Passed Label if Present
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: unit-test-passed
