name: Reusable - npm Publish

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        type: string
        default: "18.x"
      registry-url:
        description: "NPM registry URL"
        required: false
        type: string
        default: "https://registry.npmjs.org/"
      build_command:
        description: "Optional command to run to build the package before publishing (e.g., npm run build)"
        required: false
        type: string
        default: ""
      working-directory:
        description: "Directory where the package.json is located"
        required: false
        type: string
        default: "."
      runs_on:
        required: false
        type: string
        default: "self-hosted"
    secrets:
      NPM_TOKEN:
        description: "NPM authentication token"
        required: true

jobs:
  build-and-publish:
    name: Build and Publish to npm
    runs-on: ${{ inputs.runs_on }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    permissions:
      contents: read # Needed to checkout the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: "recursive"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: ${{ inputs.registry-url }}

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # npm ci might need auth for private packages

      - name: Run build command (if specified)
        if: inputs.build_command != ''
        run: ${{ inputs.build_command }}

      - name: Publish package to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run Pytest
        id: pytest
        run: |
          pytest || echo "Tests failed"
        continue-on-error: true  # Allow next steps to run even if tests fail

      - name: Label PR - Passed
        if: ${{ success() && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: unit-test-passed

      - name: Remove Failed Label if Present
        if: ${{ success() && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: unit-test-failed

      - name: Label PR - Failed
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: unit-test-failed

      - name: Remove Passed Label if Present
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: unit-test-passed
