name: QA - Set Status on Merge

on:
  pull_request:
    types: [closed]
    branches:
        - dev

jobs:
  mark-testing-pending:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/qa-update-status