name: Reusable - Set Q/A Status in Project v2

on:
  workflow_call:
    inputs:
      project_id:
        description: "GitHub Project v2 ID"
        required: true
        type: string

      item_node_id:
        description: "Node ID of the issue or PR to update"
        required: true
        type: string

      qa_field_id:
        description: "Field ID of the 'Q/A Status' field"
        required: true
        type: string

      status_option_id:
        description: "Option ID for the new Q/A Status (e.g., 'Testing In Progress')"
        required: true
        type: string

jobs:
  update-qa-status:
    name: Set QA Status on Project Item using Project v2 QA Status Field
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      pull-requests: read

    steps:
      - name: Set Q/A Status via GraphQL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          script: |
            const fs = require('fs');
            const gql = fs.readFileSync('./graphql/update-qa-status.graphql', 'utf8');
            await github.graphql(gql, {
              projectId: "${{ inputs.project_id }}",
              itemId: "${{ inputs.item_node_id }}",
              fieldId: "${{ inputs.qa_field_id }}",
              optionId: "${{ inputs.status_option_id }}"
            });