name: Reusable Metadata Sync

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
    inputs:
      sync_labels:
        required: false
        type: boolean
        default: true
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"

jobs:
  sync:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout source repo (self)
        uses: actions/checkout@v4
        with:
          repository: JamesonRGrieve/Workflows
          token: ${{ secrets.GITHUB_TOKEN }}
          path: source

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Label Sync Script
        if: ${{ inputs.sync_labels }}
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          python3 source/scripts/sync_labels.py